### ISSUE TITLE
No docker image for 8.13.4

### ISSUE THREAD

**Issue by ceeeekay** [elastic/package-registry#1183] opened 2024-05-13 23:10 UTC
Hi there,

I'm having the same issue as #1041 but for the 8.13.4 image this time. Airgapped install, attempting to pull `docker.elastic.co/package-registry/distribution:8.13.4` returns `not found: manifest unknown`.

8.13.3 was also missing up until a day or so ago, but this is working now.

I can manually pull `docker.elastic.co/package-registry/distribution:production`, but my automation is set up to pull by version number, so I'm forced to disable it when this happens as a missing image takes down my local package registry.

Is this likely to continue happening, i.e., the docker image is unavailable when an update to the rest of the stack is released?

Cheers

**Comment by kpollich** [comment] 2024-05-14 12:05
Hi @ceeeekay thanks for the issue. This was an issue with the release automation process around git tags and should be fixed soon. The release engineering team is on it and we will post an update once the latest Docker images are tagged. 

> Is this likely to continue happening, i.e., the docker image is unavailable when an update to the rest of the stack is released?

No, this was a one-off issue in the release process and the root cause is being fixed. This should not happen again and shouldn't be expected behavior.

**Comment by kpollich** [comment] 2024-05-14 16:21
Docker image should be updated now, e.g. 

![image](https://github.com/elastic/package-registry/assets/6766512/d3f227ff-c015-4661-9a3d-862bdbc82ead)

![image](https://github.com/elastic/package-registry/assets/6766512/9e128d36-c0cc-428e-abbc-b8209cbb725b)

**Closed by kpollich** 2024-05-14 16:21 UTC
Labels: bug, Team:Ecosystem

**Comment by ceeeekay** [comment] 2024-05-14 22:45
LGTM - thanks!
